.DEFAULT_GOAL = help

run:
	python manage.py runserver
tests:
	python manage.py test
parallel-tests:
	python manage.py test --parallel
reverse-tests:
	python manage.py test --reverse
help:
	@echo "=============="
	@echo "===Commands==="
	@echo "=============="
	@echo "run"
	@echo "    Run the Django server"
	@echo "tests"
	@echo "    Run all the tests"
	@echo "parallel-tests"
	@echo "    Run tests in parallel"
	@echo "reverse-tests"
	@echo "    Run tests in reverse"
